# Generated by Django 6.0.5 on 2026-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RESIDENT', 'Resident'), ('DRIVER', 'Driver'), ('STAFF_DISPATCH', 'Dispatch Staff'), ('STAFF_INVENTORY', 'Inventory Staff'), ('ADMIN', 'Admin')], default='RESIDENT', max_length=20),
        ),
    ]
