# Generated by Django 6.0.5 on 2026-05-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_designation_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_balance',
        ),
    ]
