# Generated by Django 6.0.5 on 2026-05-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterrequest',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='waterrequest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='water_requests/'),
        ),
        migrations.AlterField(
            model_name='waterrequest',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waterrequest',
            name='note',
            field=models.TextField(blank=True, help_text='Optional instructions for the driver'),
        ),
        migrations.AlterField(
            model_name='waterrequest',
            name='volume_liters',
            field=models.IntegerField(),
        ),
    ]
