# Generated by Django 6.0.5 on 2026-05-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_waterrequest_photo_url_waterrequest_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterrequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
