# Generated by Django 6.0.5 on 2026-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_waterrequest_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_liter', models.DecimalField(decimal_places=3, default=0.05, help_text='Default price per liter in USD', max_digits=10)),
                ('urgent_surcharge', models.DecimalField(decimal_places=2, default=15.0, help_text='Flat fee added for Urgent priority', max_digits=10)),
                ('critical_surcharge', models.DecimalField(decimal_places=2, default=50.0, help_text='Flat fee added for Critical priority', max_digits=10)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
