# Generated by Django 6.0.5 on 2026-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Pricing Settings', 'verbose_name_plural': 'System Pricing Settings'},
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='base_price_per_liter',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Base price per liter of water (e.g. 0.0500 = $0.05)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='critical_surcharge',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Extra flat fee added for Critical priority requests', max_digits=8),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='urgent_surcharge',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Extra flat fee added for Urgent priority requests', max_digits=8),
        ),
    ]
