# Generated by Django 6.0.5 on 2026-05-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_systemsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Pricing Settings', 'verbose_name_plural': 'System Pricing Settings'},
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
