# Generated by Django 6.0.5 on 2026-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_systemsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only ONE rate can be active at a time. This is the rate used for all new requests.'),
        ),
    ]
