# Generated by Django 6.0.5 on 2026-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_systemsettings_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_water_liters', models.BigIntegerField(default=0, help_text='Total water available in the facility (in liters)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Water Inventory',
                'verbose_name_plural': 'Water Inventory',
            },
        ),
    ]
