# Generated by Django 6.0.5 on 2026-05-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Flat fee charged for the delivery itself', max_digits=8),
        ),
    ]
