# Generated by Django 6.0.5 on 2026-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_systemsettings_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FORWARDED', 'Forwarded to Hub'), ('ON_THE_WAY', 'On The Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
