# Generated by Django 6.0.5 on 2026-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='branding_logo',
            field=models.ImageField(blank=True, help_text='Global organization logo used in footer, favicon, and PDF reports.', null=True, upload_to='branding/'),
        ),
    ]
