# Generated by Django 6.0.5 on 2026-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_inappnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='company_address',
            field=models.CharField(blank=True, help_text='Company address displayed in the footer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_email',
            field=models.EmailField(blank=True, help_text='Company contact email displayed in the footer', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='company_phone',
            field=models.CharField(blank=True, help_text='Company contact phone displayed in the footer', max_length=50, null=True),
        ),
    ]
